/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eshop;

import javax.swing.JOptionPane;

/**
 *
 * @author WildsG
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartDate = new javax.swing.JTextField();
        EndDate = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        PassTime = new javax.swing.JButton();
        StartDateLabel = new javax.swing.JLabel();
        EndDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartDate.setToolTipText("Enter Start Date in Format MM.DD.HH");

        EndDate.setToolTipText("Enter End date in format MM.DD.HH");

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        PassTime.setText("Pass Time by 1 Hour");
        PassTime.setActionCommand("PassTime");
        PassTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTimeActionPerformed(evt);
            }
        });

        StartDateLabel.setText("StartDate");

        EndDateLabel.setText("EndDate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(PassTime)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDateLabel)
                    .addComponent(EndDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StartDate)
                    .addComponent(EndDate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PassTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        EndDate.getAccessibleContext().setAccessibleDescription("Enter End Date in Format MM.DD.HH");
        StartDateLabel.getAccessibleContext().setAccessibleName("StartTimeLabel");
        EndDateLabel.getAccessibleContext().setAccessibleName("EndDateLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    TimeManager time = new TimeManager();
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        
        if(time.checkTimeInput(this.StartDate.getText(),this.EndDate.getText())!=null)
        {   
            //variables for Start/End month,day and hour respectively
            int SM; int SD; int SH;
            int EM; int ED; int EH;
            //Setting Start Date values to their variables
            try{
            SM = Integer.parseInt(this.StartDate.getText().substring(0,2));
            SD = Integer.parseInt(this.StartDate.getText().substring(3,5));
            SH = Integer.parseInt(this.StartDate.getText().substring(6,8));
            //Setting End Date values to their variables
            EM = Integer.parseInt(this.EndDate.getText().substring(0,2));
            ED = Integer.parseInt(this.EndDate.getText().substring(3,5));
            EH = Integer.parseInt(this.EndDate.getText().substring(6,8));
            //setting Start timeValue in TimeManager class
            time.setStartDate(SM,SD,SH);
            //setting End timeValue in TimeManager class
            time.setEndDate(EM,ED,EH);
            //output time
            StartDateLabel.setText("Start time is "+time.getStartMonth()+":"+ time.getStartDay()+":"+time.getStartHour());
            EndDateLabel.setText("End time is "+time.getEndMonth()+":"+ time.getEndDay()+":"+time.getEndHour());
            }
            catch(Exception e){
                //alert box if exception is caught
                 JOptionPane.showMessageDialog(null,"Exception,There were errors in time input.Try again");
            }
        }
        else
        {   
            //allert box if user inputs time incorrectly
            JOptionPane.showMessageDialog(null,"There were errors in time input.Try again");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void PassTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTimeActionPerformed
            time.setStartDate(time.getStartMonth(),time.getStartDay(), time.getStartHour()+1);
            time.setEndDate(time.getEndMonth(), time.getEndDay(), time.getEndHour()+1);
            StartDateLabel.setText("Start time is "+time.getStartMonth()+":"+ time.getStartDay()+":"+time.getStartHour());
            EndDateLabel.setText("End time is "+time.getEndMonth()+":"+ time.getEndDay()+":"+time.getEndHour());
    }//GEN-LAST:event_PassTimeActionPerformed
    
    private void ShowCurrentTime()
    {
        StartDateLabel.setText("Start time - "+time.getStartMonth()+":"+ time.getStartHour()+":"+time.getStartDay());
        EndDateLabel.setText("End time - "+time.getEndMonth()+":"+ time.getEndHour()+":"+time.getEndDay());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndDate;
    private javax.swing.JLabel EndDateLabel;
    private javax.swing.JButton PassTime;
    private javax.swing.JTextField StartDate;
    private javax.swing.JLabel StartDateLabel;
    private javax.swing.JButton UpdateButton;
    // End of variables declaration//GEN-END:variables
}
